version: '3.8'

services:
  redis:
    image: redislabs/rejson:latest
    container_name: sqlproxy_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --loadmodule /usr/lib/redis/modules/rejson.so --loadmodule /usr/lib/redis/modules/redisearch.so
    networks:
      - sqlproxy_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  sqlproxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - sqlproxy_network

networks:
  sqlproxy_network:
    name: sqlproxy_network
    driver: bridge

volumes:
  redis_data:
    name: sqlproxy_redis_data