# Prometheus configuration for SQL Proxy monitoring
# Last updated: 2025-05-20 10:10:36
# Updated by: Teeksss

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sql_proxy"
    metrics_path: /api/metrics/prometheus
    scrape_interval: 10s
    static_configs:
      - targets:
          - "sql-proxy-1:8000"
          - "sql-proxy-2:8000"
    basic_auth:
      username: "prometheus"
      password: "prom-secure-password-123"
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*):.*'
        replacement: '${1}'

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "sql-proxy-1:9100"
          - "sql-proxy-2:9100"

  - job_name: "postgres"
    static_configs:
      - targets:
          - "sql-proxy-db:9187"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

# SQL Proxy specific alerts
rule_files:
  - /etc/prometheus/rules/sql_proxy_alerts.yml