openapi: 3.0.0
info:
  title: SQLProxy API
  version: 1.0.0
  description: SQL Proxy service for secure database operations

paths:
  /api/v1/query:
    post:
      summary: Execute SQL query
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                database:
                  type: string
                  description: Database identifier
                query:
                  type: string
                  description: SQL query to execute
      responses:
        '200':
          description: Query executed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  columns:
                    type: array
                    items:
                      type: string
                  rows:
                    type: array
                    items:
                      type: object

  /api/v1/databases:
    get:
      summary: List available databases
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of databases
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT