name: Backend CI/CD (Python Poetry & Docker)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/backend-ci.yml'
    tags:
      - 'v*.*.*'
  pull_request:
    paths:
      - 'backend/**'
      - 'frontend/**'
      - 'pyproject.toml'
      - 'poetry.lock'
      - '.github/workflows/backend-ci.yml'

jobs:
  build_and_test_backend:
    name: Build, Lint, and Test Backend (Poetry from Root)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true # Creates .venv in the project root
        installer-parallel: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: ./.venv # Path to Poetry's virtualenv at the root
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies with Poetry
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true' || github.event_name == 'pull_request'
      run: poetry install --no-interaction --no-root

    - name: Check formatting with Black (via Poetry)
      run: poetry run black --check backend/

    - name: Lint with Flake8 (via Poetry)
      run: |
        poetry run flake8 backend/ --count --select=E9,F63,F7,F82 --show-source --statistics
        poetry run flake8 backend/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with Pytest (via Poetry)
      run: poetry run pytest backend/

    - name: Set up Docker Buildx
      if: github.event_name == 'pull_request'
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image for PR (Poetry from root, backend only)
      if: github.event_name == 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.backend-pr # Assumes Dockerfile.backend-pr is at root
        push: false
        tags: local/sqlproxy-backend-pr-test:latest

  build_frontend_and_package_release:
    name: Build Frontend & Package Release (Docker with Poetry from Root)
    runs-on: ubuntu-latest
    needs: build_and_test_backend
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js for Frontend Build
      uses: actions/setup-node@v4
      with:
        node-version: '18' # Adjust to your frontend's Node.js version
        cache: 'npm'       # Change to 'yarn' if you use yarn
        cache-dependency-path: frontend/package-lock.json # Change to frontend/yarn.lock if you use yarn

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm ci # Change to 'yarn install --frozen-lockfile' if you use yarn

    - name: Build Frontend Application
      working-directory: ./frontend
      run: npm run build # This should create ./frontend/dist (or similar)

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }} # Corrected to use repository_owner
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository_owner }}/sqlproxy-backend

    - name: Build and push Backend Docker image (Poetry from root, with frontend assets)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.release # Assumes Dockerfile.release is at root
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}