name: CD - Deploy to Kubernetes using Helm

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags

jobs:
  deploy_to_kubernetes:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    # environment: production # Optional: if using GitHub Environments

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Kubeconfig
      uses: azure/k8s-actions/aks-set-context@v1 # Generic, works for any K8s
      with:
        kubeconfig: ${{ secrets.KUBECONFIG_DATA }} # Secret containing your Kubeconfig data
      id: kubeconfig

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.x'
      id: helm

    - name: Get the version from the tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Deploy with Helm
      run: |
        helm upgrade --install sqlproxy \
          ./deploy/helm/sqlproxy \ # ADJUST: Path to your Helm chart
          --namespace your-namespace \ # REPLACE: your target Kubernetes namespace
          --create-namespace \
          --set image.repository=ghcr.io/${{ github.repository_owner }}/sqlproxy-backend \
          --set image.tag=${{ steps.get_version.outputs.VERSION }} \
          # --values ./deploy/helm/sqlproxy/values-production.yaml \ # Optional
          --wait # Optional
      env:
        KUBECONFIG: ${{ steps.kubeconfig.outputs.kubeconfig }}