- name: Upload partial coverage
  uses: actions/upload-artifact@v2  # v3 yerine v2 kullanın
  with:
    name: coverage-${{ matrix.python-version }}-${{ strategy.job-index }}
    path: coverage-${{ matrix.python-version }}-${{ strategy.job-index }}.xml
    if-no-files-found: warn